#!/bin/sh
# History exports
HISTSIZE=10000                              # How many lines of history to keep in memory
HISTFILE=$XDG_CACHE_HOME/zsh/history        # Where to save history to disk
SAVEHIST=10000                              # Number of history entries to save to disk
HISTDUP=erase                               # Erase duplicates in the history file

# XDG exports
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share
export XDG_STATE_HOME=$HOME/.local/state
export XDG_RUNTIME_DIR=/run/user/$UID
export WGETRC=$XDG_CONFIG_HOME/wgetrc
#export VIMRUNTIME=$XDG_CONFIG_HOME/nvim:/usr/share/nvim/runtime
export GIT_CONFIG=$XDG_CONFIG_HOME/git/config
export CARGO_HOME=$XDG_DATA_HOME/cargo
export DOCKER_CONFIG=$XDG_CONFIG_HOME/docker
export VSCODE_PORTABLE=$XDG_DATA_HOME/vscode
export STARSHIP_CONFIG=$XDG_CONFIG_HOME/starship/config.toml
export GOPATH=$XDG_DATA_HOME/go
export NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/config
export NPM_CONFIG_CACHE=$XDG_CACHE_HOME/npm
export NPM_CONFIG_TMP=$XDG_RUNTIME_DIR/npm

# Paths and default apps
export PATH=$PATH:$HOME/.local/bin:$HOME/.local/share/gem/ruby/3.0.0/bin:$HOME/.scripts:$HOME/.cargo/bin:/usr/local/go/bin
export DISTRO=$(awk -F '=' '/^ID=/ {print $2}' /etc/*-release)
export TERM='xterm-256color'
export EDITOR='nvim'
export MANPAGER='nvim +Man!'

# Change word cahracters
export WORDCHARS=${WORDCHARS/\/} # exclude slashes

# Color theme for apps
export BAT_THEME="gruvbox-dark"
